<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EFTest.Domain\EFTest.Domain.csproj" />
    <ProjectReference Include="..\EFTest.Application\EFTest.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Documents\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Documents\OrderDocument.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
